apiVersion: apps/v1
kind: Deployment
metadata:
  name: grant-api
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: grant-api
    template:
      metadata:
        labels:
          app: grant-api
      spec:
        containers:
          - name: grant-api
            image: us-docker.pkg.dev/group3-iam-project/grant-api/api-tests
            ports: 
              - containerPort: 3000
            resources:
              limits:
                cpu: ".5"
                memory: "500Mi"
              requests:
                cpu: ".25"
                memory: "250Mi"
            livenessProbe:
              httpGet:
                path: /
                port: 3000
                scheme: HTTP
              failureThreshold: 1
              periodSeconds: 10
              timeoutSeconds: 10
            startupProbe:
              httpGet:
                path: /
                port: 3000
                scheme: HTTP
              failureThreshold: 30
              periodSeconds: 10
              timeoutSeconds: 10